-- This file is auto-generated by shipwright.nvim
local common_fg = "#919191"
local dark_fg = "#121212"
local inactive_bg = "#0a0a0a"
local inactive_fg = "#4f4f4f"

return {
	normal = {
		a = { bg = "#222222", fg = common_fg, gui = "bold" },
		b = { bg = "#121212", fg = common_fg },
		c = { bg = "#0a0a0a", fg = "#4f4f4f" },
	},

	insert = {
		a = { bg = "#628282", fg = dark_fg, gui = "bold" },
	},

	command = {
		a = { bg = "#65435E", fg = common_fg, gui = "bold" },
	},

	visual = {
		a = { bg = "#5f5f5f", fg = dark_fg, gui = "bold" },
	},

	replace = {
		a = { bg = "#835d5a", fg = dark_fg, gui = "bold" },
	},

	inactive = {
		a = { bg = inactive_bg, fg = inactive_fg, gui = "bold" },
		b = { bg = inactive_bg, fg = inactive_fg },
		c = { bg = inactive_bg, fg = inactive_fg },
	},
}
