-- This file is auto-generated by shipwright.nvim
local common_fg = "#505050"
local inactive_bg = "#D4D4D4"
local inactive_fg = "#686868"

return {
	normal = {
		a = { bg = "#c6c6c6", fg = common_fg, gui = "bold" },
		b = { bg = "#d9d9d9", fg = common_fg },
		c = { bg = "#f4f4f4", fg = "#a5a5a5" },
	},

	insert = {
		a = { bg = "#A9BED1", fg = common_fg, gui = "bold" },
	},

	command = {
		a = { bg = "#DEB9D6", fg = common_fg, gui = "bold" },
	},

	visual = {
		a = { bg = "#D7D7D7", fg = common_fg, gui = "bold" },
	},

	replace = {
		a = { bg = "#EBD8DA", fg = common_fg, gui = "bold" },
	},

	inactive = {
		a = { bg = inactive_bg, fg = inactive_fg, gui = "bold" },
		b = { bg = inactive_bg, fg = inactive_fg },
		c = { bg = inactive_bg, fg = inactive_fg },
	},
}
